name: ReactionRewards
main: ro.raizen.reactionrewards.ReactionRewards
version: 1.1.2-dev
description: Reaction test and trivia with rewards !
authors: [raizenpk, makzk]
commands:
    reactionrewards:
       description: ReactionRewards main command
       aliases: rr
permissions:
    reactionrewards.*:
        description: Gives access to all /rr commands
        children:
            reactionrewards.play: true
            reactionrewards.leaderboard: true
            reactionrewards.reload: true
        default: op
    reactionrewards.play:
        description: Permission to play
        default: true
    reactionrewards.leaderboard:
        description: Can use /rr leaderboard
        default: true
    reactionrewards.start:
        description: Can use /rr start
        default: op
    reactionrewards.stop:
        description: Can use /rr stop
        default: op
    reactionrewards.reload:
        description: Can use /rr reload
        default: op
    reactionrewards.interval:
        description: Can use /rr interval
        default: op